[zookeeper]
servers=[ "zookeeper-1:2181" ]
timeout=6
root-path="/burrow"

[client-profile.myclient]
kafka-version="2.1.0"
client-id="burrow-myclient"

[cluster.local]
class-name="kafka"
servers=[ "broker-1:9092" ]
client-profile="myclient"
topic-refresh=60
offset-refresh=30

[consumer.local]
class-name="kafka"
cluster="local"
servers=[ "broker-1:9092" ]
client-profile="myclient"
group-whitelist=".*"

[httpserver.default]
address=":8000"
