 # Default values for the generator
 # this file can be used as a template for a custom configuration
 # or to know about the different variables available for the generator
      platys:
        platform-name: 'nosql-platform'
        platform-stack: 'trivadis/platys-modern-data-platform'
        platform-stack-version: '1.9.0-preview'
        structure: 'flat'

      #zookeeper
      ZOOKEEPER_enable: false
      ZOOKEEPER_volume_map_data: false
      ZOOKEEPER_nodes: 1            # either 1 or 3

      #kafka
      KAFKA_enable: false
      # one of enterprise, community
      KAFKA_edition: 'community'
      KAFKA_volume_map_data: false
      KAFKA_broker_nodes: 3
      KAFKA_delete_topic_enable: false
      KAFKA_auto_create_topics_enable: false

      #kafka schema registry
      KAFKA_SCHEMA_REGISTRY_enable: false
      KAFKA_SCHEMA_REGISTRY_nodes: 1
      KAFKA_SCHEMA_REGISTRY_use_zookeeper_election: false
      KAFKA_SCHEMA_REGISTRY_replication_factor: 1

      #kafka connect
      KAFKA_CONNECT_enable: false
      KAFKA_CONNECT_nodes: 2

      #misc kafka 'addons'
      KAFKA_KSQLDB_enable: false
      KAFKA_KSQL_edition: 'oss'
      KAFKA_KSQLDB_nodes: 1

      # Kafka Confluent Control Center
      KAFKA_CCC_enable: false

      KAFKA_RESTPROXY_enable: false
      KAFKA_MQTTPROXY_enable: false

      KAFKA_SCHEMA_REGISTRY_UI_enable: false
      KAFKA_CONNECT_UI_enable: false

      KAFKA_MANAGER_enable: false
      KAFKA_KAFDROP_enable: false
      KAFKA_KADMIN_enable: false
      KAFKA_KAFKAHQ_enable: false
      KAFKA_BURROW_enable: false

      #hadoop
      HADOOP_enable: false
      HADOOP_datanodes: 2

      #spark
      SPARK_enable: false
      SPARK_workers: 2

      # misc spark 'addons'
      SPARK_HISTORY_enable: false
      SPARK_THRIFT_enable: false
      
      # Apache Livy
      LIVY_enable: false

      # Apache Hive
      HIVE_enable: false

      # Apache Atlas
      ATLAS_enable: false
      ATLAS_provision_atlas_sample_data: false
      ATLAS_provision_amundsen_sample_data: false
      ATLAS_install_hive_hook: false

      #amundsen
      AMUNDSEN_enable: false
      # one of 'amundsen-metastore' or 'atlas-metastore'
      AMUNDSEN_edition: 'amundsen-metastore'

      #hue
      HUE_enable: false

      #streamsets and stremsets edge
      STREAMSETS_enable: false
      STREAMSETS_volume_map_data: false
      STREAMSETS_TRANSFORMER_enable: false
      STREAMSETS_TRANSFORMER_volume_map_data: false
      STREAMSETS_EDGE_enable: false
      STREAMSETS_EDGE_volume_map_data: false

      #nifi
      NIFI_enable: false

      #nodered
      NODERED_enable: false
      NODERED_volume_map_data: false

      #zeppelin
      ZEPPELIN_enable: true
      ZEPPELIN_volume_map_data: false

      #jupyter
      JUPYTER_enable: true
      # one of 'minimal', 'r', 'scipy', 'tensorflow', 'datascience', 'all_spark'
      JUPYTER_edition: 'minimal'
      JUPYTER_volume_map_data: false

      # Visualization
      GRAFANA_enable: true
      KIBANA_enable: true #needs to have elasticsearch enabled to work
      
      # NoSQL
      REDIS_enable: true
      CASSANDRA_enable: true
      DATASTAX_enable: false
      DATASTAX_nodes: 3
      MONGO_enable: true
      SOLR_enable: false
      ELASTICSEARCH_enable: true

      NEO4J_enable: true
      NEO4J_volume_map_data: false
      NEO4J_volume_map_logs: false
      
      # Influx DB 1.x
      INFLUXDB_enable: true
      INFLUXDB_volume_map_data: false
      INFLUXDB_TELEGRAF_enable: true
      INFLUXDB_CHRONOGRAF_enable: true
      INFLUXDB_CHRONOGRAF_volume_map_data: false
      INFLUXDB_KAPACITOR_enable: false
      INFLUXDB_KAPACITOR_volume_map_data: false

      # Influx DB 2.x
      INFLUXDB2_enable: false
      INFLUXDB2_volume_map_data: false

      # NoSQL - Prometeus
      PROMETHEUS_enable: false
      PROMETHEUS_volume_map_data: false
      PROMETHEUS_PUSHGATEWAY_enable: false
      
      # NoSQL - Tile38
      TILE38_enable: false

      # RDBMS
      MYSQL_enable: false
      SQLSERVER_enable: false

      POSTGRESQL_enable: true
      POSTGRESQL_volume_map_data: false
      TIMESCALEDB_enable: false
      TIMESCALEDB_volume_map_data: false

      ADMINER_enable: true

      # Event Store
      AXON_enable: false

      # ===== Presto ========
      PRESTO_enable: false
      # one of starburstdata, oss
      PRESTO_edition: 'starburstdata'

      # ===== Dremio ========
      DREMIO_enable: false

      # MQTT
      MOSQUITTO_enable: false 
      MOSQUITTO_nodes: 1
      MOSQUITTO_volume_map_data: false
      HIVEMQ3_enable: false 
      HIVEMQ4_enable: false 
      MQTT_UI_enable: false 

      # ActiveMQ
      ACTIVEMQ_enable: false

      # MinIO Object Storage
      MINIO_enable: false
      MINIO_volume_map_data: false

      AWSCLI_enable: false

      # FTP
      FTP_enable: false

      # Container Mgmt
      PORTAINER_enable: false
      CADVISOR_enable: true

      # ===== Wetty ========
      WETTY_enable: true

      # ===== Markdown Viewer ========
      MARKDOWN_VIEWER_enable: true

      # Python image
      PYTHON_enable: false
      PYTHON_script_folder: ''
      PYTHON_script: ''


